name: CI & Test

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        node-version: [20.x]
        operating-system: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Make sure to format
        run: pnpm format

      - name: Typecheck & ESLint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Build Docs
        run: pnpm build:docs

      - name: Run Unit Tests
        run: pnpm test

      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          node-version: 20.x
          folder: docs

      - name: Upload coverage report to coveralls.io...
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}          
